config/routes.rb
Rails.application.routes.draw do

  root   'static_pages#home'
  get    '/static_pages/all_movies',    to: 'static_pages#all_movies'

  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships,       only: [:create, :destroy]
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :movies, only: [:new, :create, :show, :destroy] do
    post   :comment_create
    delete :comment_destroy
  end
  resources :likes, only: [:create, :index, :destroy]
  resources :themoviedb_api, only: [:index] do
    collection do
      get :talent
      get '/talent/:id', to: 'themoviedb_api#talent_show', as: "talent_show"
    end
  end
end

app/controllers/themoviedb_api_controller.rb
require 'net/http'
require 'uri'
require 'json'

class ThemoviedbApiController < ApplicationController
  before_action :api_key, only: [:index, :talent, :talent_show]

  def index
    @title = "tmbd_api_index"
    uri = movie_list_select(params[:category])
    result = http_response_and_json_chenge(uri)
    @movies = result['results']
  end

  def talent
    unless params[:search].blank?
      key_word = URI::escape(params[:search])
      uri = "https://api.themoviedb.org/3/search/person?api_key=#{  @api_key  }&query=#{  key_word  }&page=1&include_adult=false"
      result = http_response_and_json_chenge(uri)
      @talents = result['results']
    end
  end

  def talent_show
    uri = "https://api.themoviedb.org/3/person/#{  params[:id]  }?language=en-US&api_key=#{  @api_key  }"
    @talent = http_response_and_json_chenge(uri)
  end

  private

    def api_key
      @api_key = 'bb5e93f78a09b099279afaad1fc4273d'
    end
end

app/helpers/themoviedb_api_helper.rb
module ThemoviedbApiHelper


  def movie_list_select(list)
    if "now_playing"  == list
      @list = "上映中映画一覧"
      "https://api.themoviedb.org/3/movie/now_playing?api_key=#{ @api_key }&page=1"
    elsif "top_rated" == list
      @list = "高評価順映画一覧"
      "https://api.themoviedb.org/3/movie/top_rated?api_key=#{ @api_key }&page=1"
    elsif "upcoming"  == list
      @list = "上映予定映画一覧"
      "https://api.themoviedb.org/3/movie/upcoming?api_key=#{ @api_key }&page=1"
    else
      @list = "人気順映画一覧"
      "https://api.themoviedb.org/3/movie/popular?api_key=#{ @api_key }&page=1"
    end
  end

  # HTTPリクエスト
  def http_response(uri)
    Net::HTTP.get(URI.parse(uri))
  end

  # JSONをハッシュに変換
  def http_response_and_json_chenge(uri)
    json = http_response(uri)
    JSON.parse(json)
  end

  def profile_image(image)
    if image.blank?
      "/images/dummy.png"
    else
      "//image.tmdb.org/t/p/w440_and_h660_face/#{  image  }"
    end
  end
end

app/views/themoviedb_api/_themoviedb_api.html.erb
<% if @title == "tmbd_api_index" %>
<div class="tmbd_api">
  <form action="/themoviedb_api" method="get">
    <select id="submit_select1" name="category">
      <option value="popular">人気順</option>
      <option value="top_rated">トップ評価順</option>
      <option value="now_playing">上映中の映画リスト</option>
      <option value="upcoming">上映予定の映画リスト</option>
    </select>
    <input type="submit" value="送信", class='form-control'>
  </form>
</div>
<% end %>

app/views/themoviedb_api/index.html.erb
<% provide(:title, 'TMDb_movies') %>
<div class="container-fluid">
  <h1><%= @list %></h1>
  <div class="row">
    <div class="themoviedb_api_index">
      <ul>
        <% @movies.each do |movie| %>
        <li>
            <div class="col-sm-4">
                <%= image_tag "//image.tmdb.org/t/p/w440_and_h660_face/#{  movie['poster_path']  }", class: 'image' %>
              <p>
                <%= movie['overview'] %>
              </p>
            </div>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/themoviedb_api/talent.html.erb
<% provide(:title, 'TMDb_talents') %>
<div class="TMDb_talents">
  <div class="col-md-6 col-md-offset-3">
    <h2>タレント名を入力してください</h2>
    <form class="navbar-form navbar-left" action="/themoviedb_api/talent" method="get">
      <input type="search" name="search" placeholder="キーワードを入力", class='form-control'>
      <input type="submit" name="submit" value="検索", class='form-control'>
    </form>
  </div>

  <div class="talents">
    <% unless @talents.blank? %>
    <ul class="row">
      <% @talents.each do |talent| %>
      <li class="col-sm-4">
          <%= link_to talent_show_themoviedb_api_index_path(talent['id']) do %>
            <p><%= talent['name'] %></p>
            <%= image_tag profile_image(talent['profile_path']), class: 'image' %>
          <% end %>
      </li>
      <% end %>
    </ul>
    <% else %>
    <h1>検索結果がありません</h1>
    <% end %>
  </div>
</div>

app/views/themoviedb_api/talent_show.html.erb
<% provide(:title, 'TMDb_talent_show') %>


<div class="talent_profile">
  <p class="image">
    <%= image_tag "//image.tmdb.org/t/p/w440_and_h660_face/#{  @talent['profile_path']  }"%>
  </p>
  <div>
    <h1 class="name">
      <%= @talent['name'] %>
    </h1>
    <p class="birthday">
      <span>誕生日:</span>
      <%= @talent['birthday'] %>
    </p>
    <p class="place_of_birth">
      <span>出身: </span>
      <%= @talent['place_of_birth'] %>
    </p>
    <p class="biography">
      <span>人物紹介: </span>
      <%= @talent['biography'] %>
    </p>
  </div>
</div>