config/routes.rb
Rails.application.routes.draw do

  root   'static_pages#home'
  get    '/static_pages/all_movies',    to: 'static_pages#all_movies'

  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships,       only: [:create, :destroy]
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :movies, only: [:new, :create, :show, :destroy] do
    post   :comment_create
    delete :comment_destroy
  end
  resources :likes, only: [:create, :index, :destroy]
  resources :themoviedb_api, only: [:index] do
    collection do
      get :talent
      get '/talent/:id', to: 'themoviedb_api#talent_show', as: "talent_show"
    end
  end
end

app/views/layouts/_each_link.html.erb
<div class="each_link">
  <%= render "themoviedb_api/themoviedb_api" %>
  <nav>
    <ul class="list-group">
      <li class="list-group-item"><%= link_to "プロフィール", current_user %></li>
      <li class="list-group-item"><%= link_to "映画を紹介する", new_movie_path %></li>
      <li class="list-group-item"><%= link_to "いいね一覧", likes_path %></li>
      <% if logged_in? %>
      <li class="list-group-item"><%= link_to "フォロー中", following_user_path(current_user) %></li>
      <li class="list-group-item"><%= link_to "フォロワー", followers_user_path(current_user) %></li>
      <% end %>
      <li class="list-group-item"><%= link_to "映画情報", themoviedb_api_index_path %></li>
      <li class="list-group-item"><%= link_to "タレント検索", talent_themoviedb_api_index_path %></li>
      <li class="list-group-item"><%= link_to "ホームページ",  root_path  %></li>
    </ul>
  </nav>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <p>MoviePresentation by Kota Otake</p>
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <i class="fas fa-film"></i>
    <%= link_to "MoviePresentation", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right navbar-nav mr-auto">
        <li><%= link_to "ホーム", root_path %></li>
        <li><%= link_to "投稿一覧", static_pages_all_movies_path %></li>
        <% if logged_in? %>
          <li><%= link_to "ユーザー一覧", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              アカウント <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "プロフィール", current_user %></li>
              <li><%= link_to "プロフィール設定", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <div class="main">
        <div class="each_links">
          <%= render 'layouts/each_link' %>
        </div>
        <%= yield %>
      </div>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>